Adding Markdown Feature and Updating README file - Issue #6
lyu4321/jellybean pull request #11
Opened 2021-09-23 03:58 UTC by GMOTGIT

Hello Leyang,
I added to your code the function getMdToHtml, this function works exactly like the getHtml function, but parse the markdowns to <h123> tags. 

Also updated readFile function and getUserInput function to accept .md files too.

Also, updated the README file to include the markdown feature now.

Please, let me know if I need to change anything,
Thank you so much.

2021-09-23 03:59 UTC, GMOTGIT commented
Also the required syntax is not working for me, so I had to go with import to make it work.

2021-09-23 18:03 UTC, lyu4321 commented
Hey Gustavo, thank you so much for your changes! There are just a few things I would like to mention:

- In the README, "## H3 Heading" should be ### instead of ##
- Would it be possible to add some examples of using ## and ### in the README example? 
- The getMdToHtml function is very similar to the getHtml function. Would it be possible to combine the two into one function to avoid repeating the code?

Thank you :)

2021-09-23 18:05 UTC, lyu4321 requested changes

2021-09-23 18:05 UTC, lyu4321 commented on README.md
> +| `## H3 Heading` | `<h3>H3 Heading</h3>` | <h2>H3Heading</h2>  |
Hello, there is a small typo here, it should be ### :)

2021-09-23 22:11 UTC, GMOTGIT commented
Hello Leyang,
I fixed the ReadMe.md file, sorry for the typo on line 137.
I also merged getHtml and getMdToHtml.
In order to do that I had to introduce another parameter to getHtml function so now the signature is:
getHtml (file, isTxt).
I had to do that because I could not get the type of the 'file' parameter inside the function, as it came as a string from readFile function.
So I get the file type inside readFile and pass it to getHtml.

Let me know if you are happy with these changes.
Thank you so much.

2021-09-24 00:12 UTC, merged

2021-09-24 00:12 UTC, lyu4321 commented
Hi! Thanks so much for the fixes, I've merged the PR :)